project:
  type: website

website:
  title: "adsense"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/adsense/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/adsense/
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - example.qmd