---
title: "Frequently Asked Questions"
date: "12-06-2023"
date-modified: last-modified
engine: markdown
format: 
  html:
    toc: true
---

# General Questions

## What is Quarto?

[Quarto](https://quarto.org/) is a versatile, open-source scientific and technical publishing system. Documents can be authored that
contain prose alongside of dynamic content generated by running Python, R, Julia, and Observable code.

## How can I integrate Google Adsense into my Quarto-generated website?

To integrate Google Adsense into your [Quarto](https://quarto.org/)-generated website, you can utilize the `adsense` configuration option in the YAML header of your Quarto pages or project configuration. In particular, please set the `publisher-id` key to your Google Publisher ID.

# Adsense Configuration

## Where do I find my Google Adsense publisher ID?

Your Google Adsense publisher ID is available in your Adsense account. Log in to your Adsense account, navigate to the "Settings" page, and you will find your publisher ID there.

For more details, please see Google's [Find your Publisher ID](https://support.google.com/adsense/answer/105516?hl=en) documentation.

## How do I add Google Adsense to a specific page using Quarto?

In the YAML header of the specific page where you want to add Google Adsense, include the following configuration:

```yaml
adsense:
  publisher-id: YOUR_PUBLISHER_ID

filters:
  - adsense
```

Replace `YOUR_PUBLISHER_ID` with your actual Google Adsense publisher ID. This should look similar to `ca-pub-XXXXXXXXXXXXXXXX` with the `XXXXXXXXXXXXXXXX` representing your unique ID.

## Can I prevent the placement of Adsense ads on certain webpages within my Quarto-generated website?

Yes, you can customize the placement of Adsense ads within your Quarto-generated website by setting the `enable-ads` option in the Quarto document's YAML header. 

For example, ads can be suppressed on a given by setting:

```yml
adsense:
  enable-ads: false
```

# Troubleshooting

## The ads are not appearing on my Quarto-generated website. What could be the issue?

If ads are not appearing, first ensure that your Adsense account is active and in good standing. Additionally, check the configuration in the YAML header of the specific page to confirm that the `enable-ads` or `filters` options are set appropriately. Ads may also take some time (up to an hour) to appear on the page for the first time it is opened.

## Are there any specific requirements for the Quarto version to support Google Adsense integration?

Ensure that you are using a Quarto version that supports the `adsense` Extension. This is usually checked when the extension is first installed. 

# Further Assistance

## Where can I get more help with integrating Google Adsense into my Quarto-generated website?

For additional assistance or if you encounter issues specific to Quarto or Google Adsense integration, feel free to reach out to in the project's [issue tracker](https://github.com/coatless-quarto/adsense/issues/new/choose) or consult the [official Quarto documentation](https://quarto.org/docs/guide/). Google also provides support resources for Google Adsense through their [help center](https://support.google.com/adsense#topic=3373519), [user-to-user community](https://support.google.com/adsense/community?hl=en), and [contact page](https://support.google.com/adsense/gethelp).

---

**Note:** This FAQ is intended as a general guide. Always refer to the latest [Quarto](https://quarto.org/docs/guide/) and [Google Adsense](https://support.google.com/adsense#topic=3373519)  documentation for the most up-to-date information.
