---
title: "Installation Guide for Quarto Adsense Extension"
---

## Installation

To seamlessly integrate the `adsense` extension into your Quarto project, follow these straightforward steps:

1. **Open Your Terminal:**
   Open your terminal or command prompt.

2. **Execute the Installation Command:**
   Run the following command to automatically download and install the extension:

   ```bash
   quarto add coatless-quarto/adsense
   ```

   This command installs the `adsense` extension in the `_extensions` subdirectory of your Quarto project. If you're utilizing version control, make sure to include this directory in your repository.

## Google Adsense Setup: Adding `ads.txt`

To ensure smooth integration with Google Adsense, it's essential to create a [standalone file named `ads.txt`](https://support.google.com/adsense/answer/12171612) within your project directory that identifies the domain as being authorized to serve ads. Follow these steps to include your [Google Publisher ID](https://support.google.com/adsense/answer/105516?hl=en):

1. **Create `ads.txt` File:**
   In the root of your project, create a new file named `ads.txt`.

2. **Add Google Publisher ID:**
   Open `ads.txt` and insert the following line, replacing `XXXXXXXXXXXXXXXX` with your actual Google Publisher ID:

   ```
   google.com, pub-XXXXXXXXXXXXXXXX, DIRECT, f08c47fec0942fa0
   ```

   This line informs Google's web crawler about your association with the provided Publisher ID. For an example, please see the [`docs/ads.txt`](https://github.com/coatless-quarto/adsense/blob/main/README.md).

3. **Save and Include in Version Control:**
   Save the changes to `ads.txt` and ensure that the file is included in your version control system if you're using one.

4. **Register `ads.txt` in _quarto.yml:**
   Open the `_quarto.yml` configuration and add the `resources` line under the project key.

   ```yaml
   project:
     type: website # default, book, revealjs
     resources:
       - ads.txt 
   ```

   This ensures the additional file resources are copied to the output directory.

This step is crucial for validating your ownership of the website and enabling a smooth interaction between your Quarto-generated content and Google Adsense. Remember to replace `XXXXXXXXXXXXXXXX` with your specific Google Publisher ID.

## Usage

You can configure the `adsense` extension in either of the following ways:

1. [Global Configuration Using a Configuration File](qgads-ad-localized-page.qmd):
   Set up the extension globally by incorporating the relevant configuration in either the [`_quarto.yml`](https://quarto.org/docs/projects/quarto-projects.html#project-metadata) or [`_metadata.yml`](https://quarto.org/docs/projects/quarto-projects.html#directory-metadata) file. This ensures consistent usage across all documents in your project.

2. [Document-specific Configuration in YAML Header](qgads-ad-global-configuration.qmd):
   Customize the extension settings for individual documents by adding configuration details to the YAML header of the respective Quarto document. This approach allows for fine-tuned control on a per-document basis.

Select the configuration method that best suits your project's needs to learn more!