---
title: "Release Notes"
date: "11-11-2023"
date-modified: last-modified
engine: markdown
format: 
  html:
    toc: true
---


# 2.1.0-Dev: ??? (??-??-??) [DEV]

## Documentation

- Added documentation to both the README and Installation guide detailing the setup process of `ads.txt`. ([#1](https://github.com/coatless-quarto/adsense/issues/1), h/t [@JosiahParry](https://github.com/JosiahParry))

# 2.0.0: Selective Monetize (12-06-2023)

## Features

- Added `enable-ads` option to selectively disable ads on a per-page basis when a global Google Adsense configuration is used.

```yml
adsense:
  enable-ads: false
```

## Documentation

- Reorganized getting started documentation.
- Added an example showing an ad-free page.
- Added an FAQ page.

## Deployment

- Moved the documentation website under `docs/`

# 1.0.0: Monetize (11-11-2023)

## Features

- New Google Adsense Extension for Quarto allowing for global or per-page insertion of ad units

### Installation

To install the `adsense` extension, follow these steps:

1. Open your terminal.

2. Execute the following command:

```bash
quarto add coatless-quarto/adsense
```

This command will download and install the extension under the `_extensions` subdirectory of your Quarto project. If you are using version control, ensure that you include this directory in your repository.

### Usage

Open either the [`_quarto.yml`](https://quarto.org/docs/projects/quarto-projects.html#project-metadata) or [`_metadata.yml`](https://quarto.org/docs/projects/quarto-projects.html#directory-metadata) Project file and add the following:

```yml
adsense:
  publisher-id: ca-pub-XXXXXXXXXXXXXXXX

filters:
- adsense
```

where `ca-pub-XXXXXXXXXXXXXXXX` in `publisher-id` is your Google Adsense [Publisher ID](https://support.google.com/adsense/answer/105516?hl=en).

:::{.callout-note} 
Ads may take up to an hour to appear on the page/project.
:::
